services:
  mongo:
    image: mongo:6
    container_name: cine_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - "8081:8081"
  
  ingestion:
    build:
      context: ./ingestion #Busca el Dockerfile en esta carpeta
      dockerfile: Dockerfile
    container_name: ingestion
    depends_on:
      - mongo #Asegura que MongoDB esté listo
    environment: #Inyectamos la API Key de forma segura
      - TMDB_API_KEY=e2c0b4c233e5529a10608d772dab9753
    #Cuando el script termine (la ingesta solo se ejecuta 1 vez)
    #simplemente se detenga.
    restart: "no"

volumes:
  mongo_data:
