services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - "8081:8081"
  
  api:
    build: ./api
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=cine
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  
  ingestion:
    build:
      context: ./ingestion #Busca el Dockerfile en esta carpeta
      dockerfile: Dockerfile
    depends_on:
      - mongo #Asegura que MongoDB esté listo
    environment: #Inyectamos la API Key de forma segura
      - TMDB_API_KEY=e2c0b4c233e5529a10608d772dab9753
    profiles: ["manual"]

volumes:
  mongo_data:
